name: Deploy Node.js App to Azure VM

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to the Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "/apps/solana_bot"

    - name: Install dependencies and restart the app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /apps/solana_bot
          npm install
          npm run build
          pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
